file centric configuation, next step arranger configs

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -315,10 +315,10 @@ services:
       MAESTRO_ELASTICSEARCH_CLIENT_BASICAUTH_USER: elastic
       MAESTRO_ELASTICSEARCH_CLIENT_BASICAUTH_PASSWORD: myelasticpassword
       MAESTRO_ELASTICSEARCH_CLIENT_TRUSTSELFSIGNCERT: true
-      MAESTRO_ELASTICSEARCH_INDEXES_ANALYSISCENTRIC_NAME: analysis-composer-index
-      MAESTRO_ELASTICSEARCH_INDEXES_ANALYSISCENTRIC_ALIAS: analysis_centric
       MAESTRO_ELASTICSEARCH_INDEXES_ANALYSISCENTRIC_ENABLED: false
       MAESTRO_ELASTICSEARCH_INDEXES_FILECENTRIC_ENABLED: true
+      MAESTRO_ELASTICSEARCH_INDEXES_FILECENTRIC_NAME: overture-composer-index
+      MAESTRO_ELASTICSEARCH_INDEXES_FILECENTRIC_ALIAS: file_centric
       MAESTRO_ELASTICSEARCH_CLIENT_BASICAUTH_ENABLED: true
       MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
       # Spring Variables
@@ -373,14 +373,27 @@ services:
     ports:
       - "9201:9201"
     volumes:
-      - ./configurationFiles/elasticsearchConfigs/composer_index_template.json:/usr/share/elasticsearch/config/composer_index_template.json
-    # add in scripting to check if a template already exists this will reduce the need to rerun when restarting
+      - ./configurationFiles/elasticsearchConfigs/quickstart_index_template.json:/usr/share/elasticsearch/config/quickstart_index_template.json
     command: >
       sh -c "
       apk --no-cache add curl && 
       sleep 60 && 
-      curl -u elastic:myelasticpassword -X PUT 'http://elasticsearch:9200/_template/index_template' -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/config/composer_index_template.json && 
-      curl -u elastic:myelasticpassword -X PUT 'http://elasticsearch:9200/analysis-composer-index' -H 'Content-Type: application/json' -d '{\"aliases\": {\"analysis_centric\": {\"is_write_index\": true}}}'
+      if ! curl -s -u elastic:myelasticpassword 'http://elasticsearch:9200/_template/index_template' | grep -q '\"index_patterns\"'; then 
+        curl -u elastic:myelasticpassword -X PUT 'http://elasticsearch:9200/_template/index_template' -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/config/quickstart_index_template.json &&
+        echo 'Template created successfully.'; 
+      else 
+        echo 'Template already exists, skipping creation.'; 
+      fi &&
+      if curl -s -o /dev/null -w '%{http_code}' -u elastic:myelasticpassword -X PUT 'http://elasticsearch:9200/overture-quickstart-index' -H 'Content-Type: application/json' -d '{\"aliases\": {\"file_centric\": {\"is_write_index\": true}}}' | grep -q '200'; then 
+        echo 'Alias created successfully.'; 
+      else 
+        if curl -s -o /dev/null -w '%{http_code}' -u elastic:myelasticpassword -X GET 'http://elasticsearch:9200/overture-composer-index' | grep -q '200'; then
+          echo 'Alias already exists, skipping creation.';
+        else
+          echo 'Failed to create alias.'; 
+          exit 1; 
+        fi
+      fi
       " 
     networks:
       - frontend-network
@@ -454,8 +467,8 @@ services:
       # Score Variables
       NEXT_PUBLIC_SCORE_API_URL: http://score:8087
       # Arranger Variables
-      NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: analysis
-      NEXT_PUBLIC_ARRANGER_INDEX: analysis_centric
+      NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: file
+      NEXT_PUBLIC_ARRANGER_INDEX: file_centric
       NEXT_PUBLIC_ARRANGER_API_URL: http://arranger-server:5050
       NEXT_PUBLIC_ARRANGER_MANIFEST_COLUMNS: repositories.code, analysis.analysis_id, object_id, file.index_file.file_type, file.index_file.name, file.index_file.size, file.index_file.md5sum, file.index_file.object_id, donors.donor_id, donors.specimens.samples.sample_id, study_id
     networks:
