🎻 Conductor Update (Development environment automations) (#20)

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,10 +1,6 @@
 services:
-  # ======================================
-  # Conductor 
-  # --------------------------------------
-  # Orchestrates setup with health checks, data population and logging
-  # --------------------------------------
   conductor:
+    profiles: ["platform", "songDev", "scoreDev", "maestroDev", "arrangerDev", "stageDev"]
     image: alpine/curl:8.8.0
     container_name: conductor
     ports:
@@ -13,124 +9,59 @@ services:
       - ./persistentStorage/data-keycloak-db:/keycloak/db-folder-init
       - ./persistentStorage/data-song-db:/song/db-folder-init
       - ./configurationFiles/elasticsearchConfigs/quickstart_index_template.json:/usr/share/elasticsearch/config/quickstart_index_template.json
+      - ./configurationFiles/elasticsearchConfigs/es-docs:/es-docs
+      - ./conductorScripts:/scripts
       - ./health:/health
+    environment:
+      - PROFILE=${PROFILE:-platform}
     command: >
       sh -c '
         set -e
-
-        echo -e "\033[1;36m╔══════════════════════════════════════════╗\033[0m"
-        echo -e "\033[1;36m║    Welcome to the Overture QuickStart    ║\033[0m"
-        echo -e "\033[1;36m╚══════════════════════════════════════════╝\033[0m"
-        # Create missing empty directories not tracked by git and needed by postgres
-        echo -e "\033[1;35m[1/7]\033[0m Setting up empty directories for postgres"
-        mkdir -p keycloak/db-folder-init/pg_tblspc
-        mkdir -p keycloak/db-folder-init/pg_stat
-        mkdir -p keycloak/db-folder-init/pg_replslot
-        mkdir -p keycloak/db-folder-init/pg_dynshmem
-        mkdir -p keycloak/db-folder-init/pg_twophase
-        mkdir -p keycloak/db-folder-init/pg_notify
-        mkdir -p keycloak/db-folder-init/pg_serial
-        mkdir -p keycloak/db-folder-init/pg_snapshots
-        mkdir -p keycloak/db-folder-init/pg_commit_ts
-        mkdir -p keycloak/db-folder-init/pg_wal/archive_status
-        mkdir -p keycloak/db-folder-init/pg_logical/snapshots
-        mkdir -p keycloak/db-folder-init/pg_logical/mappings
-        mkdir -p song/db-folder-init/pg_tblspc
-        mkdir -p song/db-folder-init/pg_stat
-        mkdir -p song/db-folder-init/pg_replslot
-        mkdir -p song/db-folder-init/pg_twophase
-        mkdir -p song/db-folder-init/pg_snapshots
-        mkdir -p song/db-folder-init/pg_commit_ts
-        mkdir -p song/db-folder-init/pg_logical/snapshots
-        mkdir -p song/db-folder-init/pg_logical/mappings
-        echo -e "\033[1;32mSuccess:\033[0m Databases ready"
-
-        # Wait for Elasticsearch
-        echo -e "\033[1;35m[2/7]\033[0m Waiting for Elasticsearch (this may take a few minutes)"
-        sleep 20
-        until curl -s -u elastic:myelasticpassword -X GET "http://elasticsearch:9200/_cluster/health" > /dev/null; do
-          echo -e "\033[1;36mElasticsearch:\033[0m Not yet reachable, checking again in 30 seconds"
-          sleep 30
-        done
-        echo -e "\033[1;32mSuccess:\033[0m Elasticsearch is reachable"
-
-        # Set up Elasticsearch index template
-        echo -e "\033[1;35m[3/7]\033[0m Setting up Elasticsearch index template"
-        if ! curl -s -u elastic:myelasticpassword "http://elasticsearch:9200/_template/index_template" | grep -q "\"index_patterns\"" > /dev/null; then 
-          curl -s -u elastic:myelasticpassword -X PUT "http://elasticsearch:9200/_template/index_template" -H "Content-Type: application/json" -d @/usr/share/elasticsearch/config/quickstart_index_template.json > /dev/null &&
-          echo -e "\033[1;32mSuccess:\033[0m Elasticsearch index template created successfully"
-        else
-          echo -e "\033[1;36mElasticsearch:\033[0m Index template already exists, skipping creation"
-        fi
-
-        # Set up Elasticsearch index and alias (needs failure check)
-        echo -e "\033[1;35m[4/7]\033[0m Setting up Elasticsearch index and alias"
-        echo -e "\033[1;36mElasticsearch:\033[0m Checking if Elasticsearch index exists"
-        if ! curl -s -f -u elastic:myelasticpassword -X GET "http://elasticsearch:9200/overture-quickstart-index" > /dev/null 2>&1; then
-          echo -e "\033[1;32mElasticsearch:\033[0m Creating Elasticsearch index and alias"
-          response=$$(curl -s -w "\n%{http_code}" -u elastic:myelasticpassword -X PUT "http://elasticsearch:9200/overture-quickstart-index" -H "Content-Type: application/json" -d "{\"aliases\": {\"file_centric\": {\"is_write_index\": true}}}")
-          http_code=$$(echo "$$response" | tail -n1)
-          body=$$(echo "$$response" | sed "$$d")
-          echo -e "\033[1;32mSuccess:\033[0m Index and alias created successfully, Elasticsearch setup complete"
-        else
-          echo -e "\033[1;36mElasticsearch:\033[0m Index already exists, skipping creation"
-        fi
-
-        # Check for Song
-        echo -e "\033[1;35m[5/7]\033[0m Checking if Song is ready" 
-        until [ "$(curl -s -o /dev/null -w "%{http_code}" "http://song:8080/isAlive" -H "accept: */*")" = "200" ]; do
-          echo -e "\033[1;36mSong:\033[0m Not yet reachable, checking again in 2 seconds"
-          sleep 20
-        done
-        echo -e "\033[1;32mSuccess:\033[0m Song is now reachable"
-        
-        # Updating health status of the conductor image
-        # This health file signals container readiness, fulfilling dependencies for search & discovery components, Maestro, Arranger & Stage
-        echo "healthy" > /health/conductor_health
-        echo -e  "\033[1;36mConductor:\033[0m Updating Container Status. Health check file created"
-
-        # Check Maestro
-        echo -e "\033[1;35m[6/8]\033[0m Checking if Maestro is reachable (this may take a few minutes)" 
-        until curl -s -X POST "http://maestro:11235/index/repository/song.overture/study/demo" -H "accept: */*" -d "{}" | grep -q "true"; do
-          echo -e "\033[1;36mMaestro:\033[0m Not yet reachable, checking again in 30 seconds"
-          sleep 30
-        done
-        echo -e "\033[1;32mSuccess:\033[0m Maestro is now reachable"
-
-        # Check Arranger
-        echo -e "\033[1;35m[7/8]\033[0m Checking if Arranger is reachable"
-        until curl -s -o /dev/null -w "%{http_code}" "http://arranger-server:5050/graphql" | grep -q "200"; do
-          echo -e "\033[1;36mArranger:\033[0m Not yet reachable, checking again in 10 seconds"
-          sleep 10
-        done
-        echo -e "\033[1;32mSuccess:\033[0m Arranger is now reachable"
-
-        # Check Stage
-        echo -e "\033[1;35m[8/8]\033[0m Checking if Stage is reachable"
-        until curl -s -o /dev/null -w "%{http_code}" "http://stage:3000" | grep -q "200"; do
-          echo -e "\033[1;36mStage:\033[0m Not yet reachable, checking again in 10 seconds"
-          sleep 10
-        done
-        echo -e "\033[1;32mSuccess:\033[0m Stage is now reachable"
-        echo -e "\033[1;36m╔══════════════════════════════════════════╗\033[0m"
-        echo -e "\033[1;36m║    Overture QuickStart Setup Complete    ║\033[0m"
-        echo -e "\033[1;36m╚══════════════════════════════════════════╝\033[0m"
-        echo -e "\033[1m🌐 Front-end Portal:\033[0m"
-        echo -e "   \033[1;32mhttp://localhost:3000\033[0m\n"
-        echo -e "\033[1m📚 Overture Platform Guides:\033[0m"
-        echo -e "   \033[1;32mhttps://www.overture.bio/documentation/guides/\033[0m\n"
-        echo -e "\033[1m🛠️ QuickStart Information:\033[0m"
-        echo -e "   Check the \033[1;33mdocker-compose.yml\033[0m file for details on this QuickStart,"
-        echo -e "   including links to relevant sections of our deployment guide.\n"
-        rm /health/conductor_health
+          echo "Profile is set to: $PROFILE"
+          case "$PROFILE" in
+            platform)
+              echo "Running platform deployment..."
+              chmod +x scripts/deployments/platform.sh
+              scripts/deployments/platform.sh
+              ;;
+            stageDev)
+              echo "Running Stage development environment..."
+              chmod +x scripts/deployments/stageDev.sh
+              scripts/deployments/stageDev.sh
+              ;;
+            arrangerDev)
+              echo "Running Arranger development environment..."
+              chmod +x scripts/deployments/arrangerDev.sh
+              scripts/deployments/arrangerDev.sh
+              ;;
+            maestroDev)
+              echo "Running Maestro development environment..."
+              chmod +x scripts/deployments/maestroDev.sh
+              scripts/deployments/maestroDev.sh
+              ;;
+            songDev)
+              echo "Running Song development environment..."
+              chmod +x scripts/deployments/songDev.sh
+              scripts/deployments/songDev.sh
+              ;;
+            scoreDev)
+              echo "Running Score development environment..."
+              chmod +x scripts/deployments/scoreDev.sh
+              scripts/deployments/scoreDev.sh
+              ;;
+            *)
+              echo "Invalid profile: $PROFILE. Available options are [platform, songDev, scoreDev, maestroDev, arrangerDev, stageDev]."
+              exit 1
+              ;;
+          esac
         exit 0
       '
     healthcheck:
       test: ["CMD", "test", "-f", "/health/conductor_health"]
-      interval: 30s
-      timeout: 10s
+      interval: 5s
+      timeout: 40s
       retries: 100
-      start_period: 45s
+      start_period: 30s
 
   # ==================================================================================
   # OAuth (KeyCloak)
@@ -139,15 +70,16 @@ services:
   # ======================================
   # Keycloak Database
   # --------------------------------------
-  # Pre-populated with a system side API key: 68fb42b4-f1ed-4e8c-beab-3724b99fe528, required for Songs SCORE_ACCESSTOKEN env variable
+  # Pre-populated with a system wide API key: 68fb42b4-f1ed-4e8c-beab-3724b99fe528, required for Songs SCORE_ACCESSTOKEN env variable
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/oauth/#setting-up-the-keycloak-database
   # --------------------------------------
   keycloak-db:
+    profiles: ["platform", "songDev" , "scoreDev" ,"maestroDev", "stageDev"]
     depends_on:
       - conductor
     image: postgres:14
-    container_name: keycloak-db
     platform: linux/amd64
+    container_name: keycloak-db
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin123
@@ -168,6 +100,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/oauth/#setting-up-keycloak
   # --------------------------------------
   keycloak:
+    profiles: ["platform", "songDev", "scoreDev", "maestroDev", "stageDev"]
     image: quay.io/keycloak/keycloak:22.0
     container_name: keycloak
     platform: linux/amd64
@@ -207,31 +140,60 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/datamanagement/#running-kafka
   # --------------------------------------
   kafka:
-    image: confluentinc/cp-kafka:7.6.1
-    container_name: kafka
-    platform: linux/amd64
-    ports:
-      - "9092:9092"
-      - "29092:29092"
-    environment:
-      KAFKA_PROCESS_ROLES: broker,controller
-      KAFKA_NODE_ID: 1
-      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
-      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
-      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
-      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
-      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
-      KAFKA_LOG_DIRS: /var/lib/kafka/data
-      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
-      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
-      KAFKA_NUM_PARTITIONS: 1
-      CLUSTER_ID: "q1Sh-9_ISia_zwGINzRvyQ"
-    healthcheck:
-      test: ["CMD", "sh", "-c", "echo stats | nc localhost 9092"]
-      interval: 30s
-      timeout: 10s
-      retries: 5
+      profiles: ["platform", "maestroDev"]
+      image: confluentinc/cp-kafka:7.6.1
+      container_name: kafka
+      platform: linux/amd64
+      ports:
+        - "9092:9092"
+        - "29092:29092"
+      volumes:
+        - ./conductorScripts/services/kafkaSetup.sh:/scripts/kafkaSetup.sh
+      environment:
+        # Core Kafka Configuration
+        KAFKA_PROCESS_ROLES: broker,controller
+        KAFKA_NODE_ID: 1
+        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
+        KAFKA_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://kafka:9093
+        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
+        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
+        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
+        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
+        # Storage Configuration
+        KAFKA_LOG_DIRS: /var/lib/kafka/data
+        KAFKA_LOG_RETENTION_HOURS: 168  # 7 days
+        KAFKA_LOG_RETENTION_BYTES: -1   # Unlimited size
+        # Topic Configuration
+        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+        KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
+        KAFKA_NUM_PARTITIONS: 1
+        KAFKA_DEFAULT_REPLICATION_FACTOR: 1
+        KAFKA_MIN_INSYNC_REPLICAS: 1
+        # Performance Tuning
+        KAFKA_MESSAGE_MAX_BYTES: 5242880  # 5MB max message size
+        KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
+        # Logging Configuration
+        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
+        KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
+        # Cluster Configuration
+        CLUSTER_ID: "q1Sh-9_ISia_zwGINzRvyQ" 
+      command: >
+        sh -c '
+          echo "Setting up Kafka..."
+          chmod +x /scripts/kafkaSetup.sh
+          /scripts/kafkaSetup.sh &
+          
+          # Start Kafka broker
+          /etc/confluent/docker/run
+        '
+      healthcheck:
+        test: 
+          - "CMD-SHELL"
+          - >
+            /bin/kafka-topics --bootstrap-server kafka:9092 --list
+        interval: 10s
+        timeout: 5s
+        retries: 10
 
   # ======================================
   # Song Database
@@ -240,11 +202,14 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/datamanagement/#running-song
   # --------------------------------------
   song-db:
+    profiles: ["platform", "songDev", "scoreDev", "maestroDev"]
+    depends_on:
+      - conductor
     image: postgres:11.1
     container_name: song-db
     platform: linux/amd64
-    depends_on:
-      - conductor
+    ports: 
+      - "5433:5432"
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin123
@@ -265,6 +230,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/datamanagement/#running-song
   # --------------------------------------
   song:
+    profiles: ["platform", "scoreDev", "maestroDev"]
     image: ghcr.io/overture-stack/song-server:5.2.0
     container_name: song
     platform: linux/amd64
@@ -272,7 +238,7 @@ services:
       keycloak:
         condition: service_started
       kafka:
-        condition: service_started
+        condition: service_healthy
       song-db:
         condition: service_healthy
     ports:
@@ -305,7 +271,7 @@ services:
       SPRING_DATASOURCE_USERNAME: admin
       SPRING_DATASOURCE_PASSWORD: admin123
       # Kafka Variables
-      SPRING_KAFKA_BOOTSTRAPSERVERS: http://kafka:9092
+      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
       SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC: song-analysis
       # Swagger Variable
       SWAGGER_ALTERNATEURL: /swagger-api
@@ -319,6 +285,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/datamanagement/#setting-up-object-storage
   # --------------------------------------
   minio:
+    profiles: ["platform", "scoreDev", "songDev", "maestroDev"]
     image: minio/minio:RELEASE.2018-05-11T00-29-24Z
     container_name: minio
     platform: linux/amd64
@@ -343,13 +310,12 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/datamanagement/#running-score
   # --------------------------------------
   score:
+    profiles: ["platform", "songDev", "maestroDev"]
     image: ghcr.io/overture-stack/score-server:5.11.0
     container_name: score
     platform: linux/amd64
     depends_on:
       keycloak:
-        condition: service_started
-      song:
         condition: service_started
     ports:
       - "8087:8087"
@@ -399,6 +365,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#setting-up-elasticsearch
   # --------------------------------------
   elasticsearch:
+    profiles: ["platform", "stageDev", "arrangerDev", "maestroDev"]
     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
     container_name: elasticsearch
     platform: linux/amd64
@@ -431,6 +398,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-maestro
   # --------------------------------------
   maestro:
+    profiles: ["platform"]
     image: ghcr.io/overture-stack/maestro:4.3.0
     container_name: maestro
     platform: linux/amd64
@@ -453,7 +421,7 @@ services:
       MAESTRO_REPOSITORIES_0_CODE: song.overture
       MAESTRO_REPOSITORIES_0_URL: http://song:8080
       MAESTRO_REPOSITORIES_0_NAME: Overture
-      MAESTRO_REPOSITORIES_0_ORGANIZATION: Overture
+      MAESTRO_REPOSITORIES_0_ORGANIZATION: OICR
       MAESTRO_REPOSITORIES_0_COUNTRY: CA
       # Elasticsearch Variables
       MAESTRO_ELASTICSEARCH_CLUSTER_NODES: http://elasticsearch:9200
@@ -465,7 +433,7 @@ services:
       MAESTRO_ELASTICSEARCH_INDEXES_FILECENTRIC_NAME: overture-quickstart-index
       MAESTRO_ELASTICSEARCH_INDEXES_FILECENTRIC_ALIAS: file_centric
       MAESTRO_ELASTICSEARCH_CLIENT_BASICAUTH_ENABLED: true
-      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
+      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: false
       # Spring Variables
       SPRING_MVC_ASYNC_REQUESTTIMEOUT: -1
       SPRINGDOC_SWAGGERUI_PATH: /swagger-api
@@ -480,6 +448,7 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-arranger
   # --------------------------------------
   arranger-server:
+    profiles: ["platform", "stageDev"]
     image: ghcr.io/overture-stack/arranger-server:3.0.0-beta.33
     container_name: arranger-server
     platform: linux/amd64
@@ -501,9 +470,6 @@ services:
       ES_HOST: http://elasticsearch:9200
       ES_USER: elastic
       ES_PASS: myelasticpassword
-      # Stage Variables
-      REACT_APP_BASE_URL: http://stage:3000
-      REACT_APP_ARRANGER_ADMIN_ROOT: http://arranger-server:5050/graphql
     
   # ==================================================================================
   #  F. Discovery (Stage)
@@ -516,14 +482,13 @@ services:
   # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#setting-up-stage
   # --------------------------------------
   stage:
+    profiles: ["platform", "arrangerDev"]
     image: ghcr.io/overture-stack/stage:a211593
     container_name: stage
     platform: linux/amd64
     depends_on:
       conductor:
         condition: service_healthy
-      arranger-server:
-        condition: service_started
     ports:
       - "3000:3000"
     environment:
@@ -542,8 +507,6 @@ services:
       NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: webclient
       KEYCLOAK_CLIENT_SECRET: ikksyrYaKX07acf4hpGrpKWcUGaFkEdM
       NEXT_PUBLIC_KEYCLOAK_PERMISSION_AUDIENCE: dms
-      # Score Variables
-      NEXT_PUBLIC_SCORE_API_URL: http://score:8087
       # Arranger Variables
       NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: file
       NEXT_PUBLIC_ARRANGER_INDEX: file_centric
